Name: Kubernetes
Description: |
  Kubernetes ServerTemplate
Inputs: {}
RightScripts:
  Boot:
  - Name: RL10 Linux Wait For EIP
    Revision: 5
    Publisher: RightScale
  - RS_Cluster_Init.sh
  - Name: RL10 Linux Setup Hostname
    Revision: 8
    Publisher: RightScale
  - Name: RL10 Linux Enable Managed Login
    Revision: 12
    Publisher: RightScale
  - Name: RL10 Linux Setup NTP
    Publisher: RightScale
    Revision: 1
  - Name: RL10 Linux Enable Monitoring
    Publisher: RightScale
    Revision: 8
  - Name: RL10 Linux Setup Alerts
    Publisher: RightScale
    Revision: 2
  - Name: RL10 Linux Setup Automatic Upgrade
    Publisher: RightScale
    Revision: 4
  - Kubernetes_Setup.sh
  Decommission:
  - Name: RL10 Linux Shutdown Reason
    Publisher: RightScale
    Revision: 5
  Operational:
  - Name: RL10 Linux Setup Automatic Upgrade
    Publisher: RightScale
    Revision: 4
  - Name: RL10 Linux Upgrade
    Publisher: RightScale
    Revision: 8
  - Name: RL10 Linux Enable Docker Support (Beta)
    Publisher: RightScale
    Revision: 3
  - Kubernetes_Install_Hello.sh
MultiCloudImages:
- Name: Ubuntu_16.04_x64
  Revision: 5
  Publisher: RightScale
Alerts:
- Name: rs instance terminated
  Description: Raise an alert if the instance has been terminated abnormally, i.e.
    not through the RightScale interface or by an elasticity daemon resizing server
    arrays.
  Clause: If RS/server.state == terminated for 1 minutes Then escalate critical
- Name: rs instance stranded
  Description: Raise an alert if the instance enters the stranded state.
  Clause: If RS/server-failure.state == stranded for 1 minutes Then escalate warning
- Name: rs instance not responding
  Description: Raise an alert if the instance fails to send monitoring information
    for 5 minutes.
  Clause: If cpu-0/cpu-idle.value == NaN for 5 minutes Then escalate critical
- Name: rs cpu busy
  Description: Raise an alert if the idle time is too low.
  Clause: If cpu-0/cpu-idle.value < 15 for 3 minutes Then escalate warning
- Name: rs cpu overloaded
  Description: Raise an alert when the cpu idle time is too low.
  Clause: If cpu-0/cpu-idle.value < 3 for 5 minutes Then escalate critical
- Name: rs cpu I/O wait
  Description: Raise an alert if disk io is too high.
  Clause: If cpu-0/cpu-wait.value > 40 for 15 minutes Then escalate warning
- Name: rs low space in root partition
  Description: Raise an alert if the available space in the root partition is too
    low. This alert may be modified on an instance to match the metric name df/df-root.free
    instead if the instance is running collectd 4. See the RL10 Linux Setup Alerts
    RightScript (rll/setup-alerts.sh) for more details.
  Clause: If df-root/df_complex-free.value < 1073741824 for 5 minutes Then escalate
    critical
- Name: rs high network tx activity
  Description: Raise an alert if the amount of network data transmitted is too high.
    This alert may be modified or cloned on an instance to match the actual network
    interfaces that are present. See the RL10 Linux Setup Alerts RightScript (rll/setup-alerts.sh)
    for more details.
  Clause: If interface-eth0/if_octets.tx > 10000000 for 10 minutes Then escalate critical
- Name: rs high network rx activity
  Description: Raise an alert if the amount of network data received is too high.
    This alert may be modified or cloned on an instance to match the actual network
    interfaces that are present. See the RL10 Linux Setup Alerts RightScript (rll/setup-alerts.sh)
    for more details.
  Clause: If interface-eth0/if_octets.rx > 50000000 for 30 minutes Then escalate critical
- Name: rs low swap space
  Description: Raise alert if the free swap space is too low. This alert may be removed
    from an instance if swap is not enabled. See the RL10 Linux Setup Alerts RightScript
    (rll/setup-alerts.sh) for more details.
  Clause: If swap/swap-free.value < 104857600 for 5 minutes Then escalate critical
- Name: rs memory low
  Description: Raise an alert if free memory is too low.
  Clause: If memory/memory-free.value < 1000000 for 1 minutes Then escalate critical
- Name: rs out of memory
  Description: Raise an alert when the server is out of free memory.
  Clause: If memory/memory-free.value == 0 for 1 minutes Then escalate critical
